In [1]:
import pandas as pd

In [14]:
is_2013 = pd.read_csv('processed_data/data_investment_set/investment_set_2013.csv')
is_2014 = pd.read_csv('processed_data/data_investment_set/investment_set_2014.csv')
is_2015 = pd.read_csv('processed_data/data_investment_set/investment_set_2015.csv')
is_2016 = pd.read_csv('processed_data/data_investment_set/investment_set_2016.csv')
is_2017 = pd.read_csv('processed_data/data_investment_set/investment_set_2017.csv')
is_2018 = pd.read_csv('processed_data/data_investment_set/investment_set_2018.csv')
is_2019 = pd.read_csv('processed_data/data_investment_set/investment_set_2019.csv')
is_2020 = pd.read_csv('processed_data/data_investment_set/investment_set_2020.csv')
is_2021 = pd.read_csv('processed_data/data_investment_set/investment_set_2021.csv')
is_2022 = pd.read_csv('processed_data/data_investment_set/investment_set_2022.csv')
is_2023 = pd.read_csv('processed_data/data_investment_set/investment_set_2023.csv')
is_2024 = pd.read_csv('processed_data/data_investment_set/investment_set_2024.csv')
RI_M_filtered = pd.read_csv('processed_data/data_cleaned/RI_M_filtered.csv')


# Create a new column with the proportion of each company's market value
is_2013['MV_Y_weights'] = is_2013['MV_Y'] / is_2013['MV_Y'].sum()
is_2014['MV_Y_weights'] = is_2014['MV_Y'] / is_2014['MV_Y'].sum()
is_2015['MV_Y_weights'] = is_2015['MV_Y'] / is_2015['MV_Y'].sum()
is_2016['MV_Y_weights'] = is_2016['MV_Y'] / is_2016['MV_Y'].sum()
is_2017['MV_Y_weights'] = is_2017['MV_Y'] / is_2017['MV_Y'].sum()
is_2018['MV_Y_weights'] = is_2018['MV_Y'] / is_2018['MV_Y'].sum()
is_2019['MV_Y_weights'] = is_2019['MV_Y'] / is_2019['MV_Y'].sum()
is_2020['MV_Y_weights'] = is_2020['MV_Y'] / is_2020['MV_Y'].sum()
is_2021['MV_Y_weights'] = is_2021['MV_Y'] / is_2021['MV_Y'].sum()
is_2022['MV_Y_weights'] = is_2022['MV_Y'] / is_2022['MV_Y'].sum()
is_2023['MV_Y_weights'] = is_2023['MV_Y'] / is_2023['MV_Y'].sum()
is_2024['MV_Y_weights'] = is_2024['MV_Y'] / is_2024['MV_Y'].sum()

is_2013

/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_51356/1769078423.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2013['MV_Y_weights'] = is_2013['MV_Y'] / is_2013['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_51356/1769078423.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2014['MV_Y_weights'] = is_2014['MV_Y'] / is_2014['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_51356/1769078423.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2015['MV_Y_weights'] = is_2015['MV_Y'] / is_2015['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_51356/1769078423.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2016['MV_Y_weights'] = is_2016['MV_Y'] / is_2016['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_51356/1769078423.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2017['MV_Y_weights'] = is_2017['MV_Y'] / is_2017['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_51356/1769078423.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2018['MV_Y_weights'] = is_2018['MV_Y'] / is_2018['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_51356/1769078423.py:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2019['MV_Y_weights'] = is_2019['MV_Y'] / is_2019['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_51356/1769078423.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2020['MV_Y_weights'] = is_2020['MV_Y'] / is_2020['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_51356/1769078423.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2021['MV_Y_weights'] = is_2021['MV_Y'] / is_2021['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_51356/1769078423.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2022['MV_Y_weights'] = is_2022['MV_Y'] / is_2022['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_51356/1769078423.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2023['MV_Y_weights'] = is_2023['MV_Y'] / is_2023['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_51356/1769078423.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2024['MV_Y_weights'] = is_2024['MV_Y'] / is_2024['MV_Y'].sum()

,ISIN,NAME,Country,Region,MV_Y,CO2_S1,CO2_S2,REV,Carbon_Intensity,2004-01-30 00:00:00,...,2013-04-30 00:00:00,2013-05-31 00:00:00,2013-06-28 00:00:00,2013-07-31 00:00:00,2013-08-30 00:00:00,2013-09-30 00:00:00,2013-10-31 00:00:00,2013-11-29 00:00:00,2013-12-31 00:00:00,MV_Y_weights
0,AN8068571086,SLB,US,AMER,105861.90,1790000.0,430000.0,42149000.0,0.0527,0.1181,...,-0.0061,-0.0188,-0.0146,0.1349,-0.0010,0.0917,0.0607,-0.0566,0.0227,0.005598
1,AT000000STR1,STRABAG SE,AT,EUR,3087.59,968759.0,295141.0,17782013.0,0.0711,NaN,...,0.0266,-0.0669,-0.0270,0.0828,-0.0430,0.1655,0.0549,0.1161,-0.0004,0.000163
2,AT0000606306,RAIFFEISEN BANK INTL.,AT,EUR,8185.61,5161.0,43060.0,13350128.0,0.0036,NaN,...,0.0375,-0.0315,-0.1490,0.1007,0.1284,-0.0434,0.1239,0.0031,-0.0436,0.000433
3,AT0000652011,ERSTE GROUP BANK,AT,EUR,13245.36,32753.0,84281.0,16802146.0,0.0070,0.0467,...,0.1245,0.0511,-0.1794,0.1433,0.0550,-0.0113,0.1167,-0.0010,-0.0106,0.000700
4,AT0000720008,TELEKOM AUSTRIA,AT,EUR,3381.96,27476.0,195246.0,5930020.0,0.0376,0.1377,...,0.0442,-0.0014,-0.0686,0.0974,0.0339,0.1697,-0.0169,0.0330,-0.1099,0.000179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
798,US98389B1008,XCEL ENERGY,US,AMER,13656.38,56535330.0,774475.0,10128223.0,5.6584,0.0200,...,0.0704,-0.0966,-0.0038,0.0568,-0.0678,-0.0009,0.0453,-0.0291,0.0071,0.000722
799,US9839191015,XILINX DEAD - DELIST.15/02/22,US,AMER,9719.62,1685.0,26545.0,2195457.0,0.0129,0.0847,...,-0.0068,0.0794,-0.0256,0.1787,-0.0650,0.0790,-0.0304,-0.0166,0.0335,0.000514
800,US98421M1062,XEROX HOLDINGS,US,AMER,9815.17,127000.0,186000.0,22390000.0,0.0140,0.0609,...,-0.0023,0.0245,0.0385,0.0695,0.0289,0.0367,-0.0340,0.1449,0.0744,0.000519
801,US9884981013,YUM! BRANDS,US,AMER,29787.74,156510.0,2377372.0,13633000.0,0.1859,-0.0143,...,-0.0483,-0.0054,0.0235,0.0565,-0.0398,0.0196,-0.0475,0.1488,-0.0267,0.001575
802,US98956P1021,ZIMMER BIOMET HDG.,US,AMER,12747.18,11687.0,51960.0,4471700.0,0.0142,0.0867,...,0.0163,0.0269,-0.0429,0.1139,-0.0526,0.0411,0.0649,0.0451,0.0217,0.000674

In [3]:
print(is_2013['MV_Y_weights'].sum()
,is_2014['MV_Y_weights'].sum()
,is_2015['MV_Y_weights'].sum()
,is_2016['MV_Y_weights'].sum()
,is_2017['MV_Y_weights'].sum()
,is_2018['MV_Y_weights'].sum()
,is_2019['MV_Y_weights'].sum()
,is_2020['MV_Y_weights'].sum()
,is_2021['MV_Y_weights'].sum()
,is_2022['MV_Y_weights'].sum()
,is_2023['MV_Y_weights'].sum()
,is_2024['MV_Y_weights'].sum())

0.9999999999999999 1.0 1.0 1.0 1.0 1.0 1.0 0.9999999999999999 1.0 1.0 1.0 1.0000000000000002

In [4]:
# Create the new DataFrame with the specified columns
Value_Weighted_Portfolio_2014 = is_2013[["ISIN", "NAME", "MV_Y_weights"]].copy()
# Select the last 13 columns from is_2014 and take the first 12
last_13_columns = is_2014.columns[-13:]
first_12_columns = last_13_columns[:12]

# Create a temporary DataFrame with ISIN and the selected columns
temp_df = is_2014[["ISIN"] + list(first_12_columns)]

# Merge with Value_Weighted_Portfolio_2014 on ISIN, keeping all rows from Value_Weighted_Portfolio_2014
Value_Weighted_Portfolio_2014 = pd.merge(
    Value_Weighted_Portfolio_2014,
    temp_df,
    on="ISIN",
    how="left"
)

# List of the last 12 columns (from is_2014)
last_12_columns = Value_Weighted_Portfolio_2014.columns[-12:]

# Create a new DataFrame for the results
Results_2014 = Value_Weighted_Portfolio_2014[["ISIN", "NAME", "MV_Y_weights"]].copy()

# Multiply MV_Y_weights by each of the last 12 columns and store in new columns
for col in last_12_columns:
    new_col_name = f"Weighted_{col}"
    Results_2014[new_col_name] = (
        Results_2014["MV_Y_weights"] *
        Value_Weighted_Portfolio_2014[col]
    )

# List of the last 12 weighted columns in Results_2014
weighted_columns = [col for col in Results_2014.columns if col.startswith("Weighted_")]

# Calculate the sum of each weighted column
sums = Results_2014[weighted_columns].sum().to_frame().T

# Rename the columns for clarity (optional)
sums.columns = [f"Sum_{col}" for col in sums.columns]

# Create the Returns_2014 DataFrame
Returns_2014 = sums.copy()

# Display the new DataFrame
Returns_2014

,Sum_Weighted_2014-01-31 00:00:00,Sum_Weighted_2014-02-28 00:00:00,Sum_Weighted_2014-03-31 00:00:00,Sum_Weighted_2014-04-30 00:00:00,Sum_Weighted_2014-05-30 00:00:00,Sum_Weighted_2014-06-30 00:00:00,Sum_Weighted_2014-07-31 00:00:00,Sum_Weighted_2014-08-29 00:00:00,Sum_Weighted_2014-09-30 00:00:00,Sum_Weighted_2014-10-31 00:00:00,Sum_Weighted_2014-11-28 00:00:00,Sum_Weighted_2014-12-31 00:00:00
0,-0.036073,0.054132,0.007866,0.018191,0.015617,0.011431,-0.022088,0.022326,-0.025609,0.000225,0.024581,-0.019277

In [17]:

def calculate_weighted_returns(is_weights, is_return_dfs, year_start=2014, year_end=2024):
    """
    Calculate weighted returns for each year from year_start to year_end.

    Args:
        is_weights (DataFrame): DataFrame with ISIN, NAME, and MV_Y_weights (e.g., is_2013).
        is_return_dfs (dict): Dictionary of DataFrames for each year (e.g., {"2014": is_2014, ...}).
        year_start (int): First year to process (default: 2014).
        year_end (int): Last year to process (default: 2024).

    Returns:
        dict: Dictionary of Returns DataFrames for each year.
    """
    results = {}

    for year in range(year_start, year_end + 1):
        # Create the weighted portfolio DataFrame for the current year
        Value_Weighted_Portfolio = is_weights[["ISIN", "NAME", "MV_Y_weights"]].copy()

        # Select the last 13 columns from the return DataFrame and take the first 12
        last_13_columns = is_return_dfs[str(year)].columns[-13:]
        first_12_columns = last_13_columns[:12]

        # Create a temporary DataFrame with ISIN and the selected columns
        temp_df = is_return_dfs[str(year)][["ISIN"] + list(first_12_columns)]

        # Merge with the weighted portfolio DataFrame
        Value_Weighted_Portfolio = pd.merge(
            Value_Weighted_Portfolio,
            temp_df,
            on="ISIN",
            how="left"
        )

        # List of the last 12 columns (from the return DataFrame)
        last_12_columns = Value_Weighted_Portfolio.columns[-12:]

        # Create a new DataFrame for the results
        Results = Value_Weighted_Portfolio[["ISIN", "NAME", "MV_Y_weights"]].copy()

        # Multiply MV_Y_weights by each of the last 12 columns
        for col in last_12_columns:
            new_col_name = f"Weighted_{col}"
            Results[new_col_name] = (
                Results["MV_Y_weights"] *
                Value_Weighted_Portfolio[col]
            )

        # List of the last 12 weighted columns
        weighted_columns = [col for col in Results.columns if col.startswith("Weighted_")]

        # Calculate the sum of each weighted column
        sums = Results[weighted_columns].sum().to_frame().T

        # Rename the columns for clarity
        sums.columns = [f"Sum_{col}" for col in sums.columns]

        # Store the results
        results[f"Returns_{year}"] = sums.copy()

    return results

# Example usage:
# Assume you have is_2013, is_2014, ..., is_2024 in a dictionary
is_return_dfs = {
    "2014": is_2014,
    "2015": is_2015,
    "2016": is_2016,
    "2017": is_2017,
    "2018": is_2018,
    "2019": is_2019,
    "2020": is_2020,
    "2021": is_2021,
    "2022": is_2022,
    "2023": is_2023,
    "2024": is_2024,
}

# Call the function
returns_dict = calculate_weighted_returns(is_2013, is_return_dfs)

Returns_2014 = returns_dict["Returns_2014"]
Returns_2015 = returns_dict["Returns_2015"]
Returns_2015 = returns_dict["Returns_2015"]
Returns_2016 = returns_dict["Returns_2016"]
Returns_2017 = returns_dict["Returns_2017"]
Returns_2018 = returns_dict["Returns_2018"]
Returns_2019 = returns_dict["Returns_2019"]
Returns_2020 = returns_dict["Returns_2020"]
Returns_2021 = returns_dict["Returns_2021"]
Returns_2022 = returns_dict["Returns_2022"]
Returns_2023 = returns_dict["Returns_2023"]
Returns_2024 = returns_dict["Returns_2024"] 

Returns_2014

,Sum_Weighted_2014-01-31 00:00:00,Sum_Weighted_2014-02-28 00:00:00,Sum_Weighted_2014-03-31 00:00:00,Sum_Weighted_2014-04-30 00:00:00,Sum_Weighted_2014-05-30 00:00:00,Sum_Weighted_2014-06-30 00:00:00,Sum_Weighted_2014-07-31 00:00:00,Sum_Weighted_2014-08-29 00:00:00,Sum_Weighted_2014-09-30 00:00:00,Sum_Weighted_2014-10-31 00:00:00,Sum_Weighted_2014-11-28 00:00:00,Sum_Weighted_2014-12-31 00:00:00
0,-0.036073,0.054132,0.007866,0.018191,0.015617,0.011431,-0.022088,0.022326,-0.025609,0.000225,0.024581,-0.019277