In [2]:
import pandas as pd

In [3]:
is_2013 = pd.read_csv('processed_data/data_investment_set/investment_set_2013.csv')
is_2014 = pd.read_csv('processed_data/data_investment_set/investment_set_2014.csv')
is_2015 = pd.read_csv('processed_data/data_investment_set/investment_set_2015.csv')
is_2016 = pd.read_csv('processed_data/data_investment_set/investment_set_2016.csv')
is_2017 = pd.read_csv('processed_data/data_investment_set/investment_set_2017.csv')
is_2018 = pd.read_csv('processed_data/data_investment_set/investment_set_2018.csv')
is_2019 = pd.read_csv('processed_data/data_investment_set/investment_set_2019.csv')
is_2020 = pd.read_csv('processed_data/data_investment_set/investment_set_2020.csv')
is_2021 = pd.read_csv('processed_data/data_investment_set/investment_set_2021.csv')
is_2022 = pd.read_csv('processed_data/data_investment_set/investment_set_2022.csv')
is_2023 = pd.read_csv('processed_data/data_investment_set/investment_set_2023.csv')
is_2024 = pd.read_csv('processed_data/data_investment_set/investment_set_2024.csv')
is_2025 = pd.read_csv('processed_data/data_investment_set/investment_set_2025.csv')

# Create a new column with the proportion of each company's market value
is_2013['MV_Y_weights'] = is_2013['MV_Y'] / is_2013['MV_Y'].sum()
is_2014['MV_Y_weights'] = is_2014['MV_Y'] / is_2014['MV_Y'].sum()
is_2015['MV_Y_weights'] = is_2015['MV_Y'] / is_2015['MV_Y'].sum()
is_2016['MV_Y_weights'] = is_2016['MV_Y'] / is_2016['MV_Y'].sum()
is_2017['MV_Y_weights'] = is_2017['MV_Y'] / is_2017['MV_Y'].sum()
is_2018['MV_Y_weights'] = is_2018['MV_Y'] / is_2018['MV_Y'].sum()
is_2019['MV_Y_weights'] = is_2019['MV_Y'] / is_2019['MV_Y'].sum()
is_2020['MV_Y_weights'] = is_2020['MV_Y'] / is_2020['MV_Y'].sum()
is_2021['MV_Y_weights'] = is_2021['MV_Y'] / is_2021['MV_Y'].sum()
is_2022['MV_Y_weights'] = is_2022['MV_Y'] / is_2022['MV_Y'].sum()
is_2023['MV_Y_weights'] = is_2023['MV_Y'] / is_2023['MV_Y'].sum()
is_2024['MV_Y_weights'] = is_2024['MV_Y'] / is_2024['MV_Y'].sum()
is_2025['MV_Y_weights'] = is_2025['MV_Y'] / is_2025['MV_Y'].sum()

/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_3550/3055339766.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2013['MV_Y_weights'] = is_2013['MV_Y'] / is_2013['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_3550/3055339766.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2014['MV_Y_weights'] = is_2014['MV_Y'] / is_2014['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_3550/3055339766.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2015['MV_Y_weights'] = is_2015['MV_Y'] / is_2015['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_3550/3055339766.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2016['MV_Y_weights'] = is_2016['MV_Y'] / is_2016['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_3550/3055339766.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2017['MV_Y_weights'] = is_2017['MV_Y'] / is_2017['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_3550/3055339766.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2018['MV_Y_weights'] = is_2018['MV_Y'] / is_2018['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_3550/3055339766.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2019['MV_Y_weights'] = is_2019['MV_Y'] / is_2019['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_3550/3055339766.py:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2020['MV_Y_weights'] = is_2020['MV_Y'] / is_2020['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_3550/3055339766.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2021['MV_Y_weights'] = is_2021['MV_Y'] / is_2021['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_3550/3055339766.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2022['MV_Y_weights'] = is_2022['MV_Y'] / is_2022['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_3550/3055339766.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2023['MV_Y_weights'] = is_2023['MV_Y'] / is_2023['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_3550/3055339766.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2024['MV_Y_weights'] = is_2024['MV_Y'] / is_2024['MV_Y'].sum()
/var/folders/b3/wvshm2ws24dc4b18w65382sh0000gn/T/ipykernel_3550/3055339766.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  is_2025['MV_Y_weights'] = is_2025['MV_Y'] / is_2025['MV_Y'].sum()

In [4]:
print(is_2013['MV_Y_weights'].sum()
,is_2014['MV_Y_weights'].sum()
,is_2015['MV_Y_weights'].sum()
,is_2016['MV_Y_weights'].sum()
,is_2017['MV_Y_weights'].sum()
,is_2018['MV_Y_weights'].sum()
,is_2019['MV_Y_weights'].sum()
,is_2020['MV_Y_weights'].sum()
,is_2021['MV_Y_weights'].sum()
,is_2022['MV_Y_weights'].sum()
,is_2023['MV_Y_weights'].sum()
,is_2024['MV_Y_weights'].sum()
,is_2025['MV_Y_weights'].sum())

0.9999999999999999 1.0 1.0 1.0 1.0 1.0 1.0 0.9999999999999999 1.0 1.0 1.0 1.0000000000000002 1.0

In [5]:
# Create the new DataFrame with the specified columns
Value_Weighted_Portfolio_2014 = is_2013[["ISIN", "NAME", "MV_Y_weights"]].copy()
# Select the last 13 columns from is_2014 and take the first 12
last_13_columns = is_2014.columns[-13:]
first_12_columns = last_13_columns[:12]

# Create a temporary DataFrame with ISIN and the selected columns
temp_df = is_2014[["ISIN"] + list(first_12_columns)]

# Merge with Value_Weighted_Portfolio_2014 on ISIN, keeping all rows from Value_Weighted_Portfolio_2014
Value_Weighted_Portfolio_2014 = pd.merge(
    Value_Weighted_Portfolio_2014,
    temp_df,
    on="ISIN",
    how="left"
)

# List of the last 12 columns (from is_2014)
last_12_columns = Value_Weighted_Portfolio_2014.columns[-12:]

# Create a new DataFrame for the results
Results_2014 = Value_Weighted_Portfolio_2014[["ISIN", "NAME", "MV_Y_weights"]].copy()

# Multiply MV_Y_weights by each of the last 12 columns and store in new columns
for col in last_12_columns:
    new_col_name = f"Weighted_{col}"
    Results_2014[new_col_name] = (
        Results_2014["MV_Y_weights"] *
        Value_Weighted_Portfolio_2014[col]
    )

# List of the last 12 weighted columns in Results_2014
weighted_columns = [col for col in Results_2014.columns if col.startswith("Weighted_")]

# Calculate the sum of each weighted column
sums = Results_2014[weighted_columns].sum().to_frame().T

# Rename the columns for clarity (optional)
sums.columns = [f"Sum_{col}" for col in sums.columns]

# Create the Returns_2014 DataFrame
Returns_2014 = sums.copy()

# Display the new DataFrame
Returns_2014

,Sum_Weighted_2014-01-31 00:00:00,Sum_Weighted_2014-02-28 00:00:00,Sum_Weighted_2014-03-31 00:00:00,Sum_Weighted_2014-04-30 00:00:00,Sum_Weighted_2014-05-30 00:00:00,Sum_Weighted_2014-06-30 00:00:00,Sum_Weighted_2014-07-31 00:00:00,Sum_Weighted_2014-08-29 00:00:00,Sum_Weighted_2014-09-30 00:00:00,Sum_Weighted_2014-10-31 00:00:00,Sum_Weighted_2014-11-28 00:00:00,Sum_Weighted_2014-12-31 00:00:00
0,-0.036073,0.054132,0.007866,0.018191,0.015617,0.011431,-0.022088,0.022326,-0.025609,0.000225,0.024581,-0.019277

In [7]:

def calculate_weighted_returns(is_weights, is_return_dfs, year_start=2014, year_end=2025):
    """
    Calculate weighted returns for each year from year_start to year_end.

    Args:
        is_weights (DataFrame): DataFrame with ISIN, NAME, and MV_Y_weights (e.g., is_2013).
        is_return_dfs (dict): Dictionary of DataFrames for each year (e.g., {"2014": is_2014, ...}).
        year_start (int): First year to process (default: 2014).
        year_end (int): Last year to process (default: 2025).

    Returns:
        dict: Dictionary of Returns DataFrames for each year.
    """
    results = {}

    for year in range(year_start, year_end + 1):
        # Create the weighted portfolio DataFrame for the current year
        Value_Weighted_Portfolio = is_weights[["ISIN", "NAME", "MV_Y_weights"]].copy()

        # Select the last 13 columns from the return DataFrame and take the first 12
        last_13_columns = is_return_dfs[str(year)].columns[-13:]
        first_12_columns = last_13_columns[:12]

        # Create a temporary DataFrame with ISIN and the selected columns
        temp_df = is_return_dfs[str(year)][["ISIN"] + list(first_12_columns)]

        # Merge with the weighted portfolio DataFrame
        Value_Weighted_Portfolio = pd.merge(
            Value_Weighted_Portfolio,
            temp_df,
            on="ISIN",
            how="left"
        )

        # List of the last 12 columns (from the return DataFrame)
        last_12_columns = Value_Weighted_Portfolio.columns[-12:]

        # Create a new DataFrame for the results
        Results = Value_Weighted_Portfolio[["ISIN", "NAME", "MV_Y_weights"]].copy()

        # Multiply MV_Y_weights by each of the last 12 columns
        for col in last_12_columns:
            new_col_name = f"Weighted_{col}"
            Results[new_col_name] = (
                Results["MV_Y_weights"] *
                Value_Weighted_Portfolio[col]
            )

        # List of the last 12 weighted columns
        weighted_columns = [col for col in Results.columns if col.startswith("Weighted_")]

        # Calculate the sum of each weighted column
        sums = Results[weighted_columns].sum().to_frame().T

        # Rename the columns for clarity
        sums.columns = [f"Sum_{col}" for col in sums.columns]

        # Store the results
        results[f"Returns_{year}"] = sums.copy()

    return results

# Example usage:
# Assume you have is_2013, is_2014, ..., is_2024 in a dictionary
is_return_dfs = {
    "2014": is_2014,
    "2015": is_2015,
    "2016": is_2016,
    "2017": is_2017,
    "2018": is_2018,
    "2019": is_2019,
    "2020": is_2020,
    "2021": is_2021,
    "2022": is_2022,
    "2023": is_2023,
    "2024": is_2024,
    "2025": is_2025
}

# Call the function
returns_dict = calculate_weighted_returns(is_2013, is_return_dfs)

Returns_2014 = returns_dict["Returns_2014"]
Returns_2015 = returns_dict["Returns_2015"]
Returns_2015 = returns_dict["Returns_2015"]
Returns_2016 = returns_dict["Returns_2016"]
Returns_2017 = returns_dict["Returns_2017"]
Returns_2018 = returns_dict["Returns_2018"]
Returns_2019 = returns_dict["Returns_2019"]
Returns_2020 = returns_dict["Returns_2020"]
Returns_2021 = returns_dict["Returns_2021"]
Returns_2022 = returns_dict["Returns_2022"]
Returns_2023 = returns_dict["Returns_2023"]
Returns_2024 = returns_dict["Returns_2024"] 
Returns_2025 = returns_dict["Returns_2025"]
Returns_2025

,Sum_Weighted_2025-01-31 00:00:00,Sum_Weighted_2025-02-28 00:00:00,Sum_Weighted_2025-03-31 00:00:00,Sum_Weighted_2025-04-30 00:00:00,Sum_Weighted_2025-05-30 00:00:00,Sum_Weighted_2025-06-30 00:00:00,Sum_Weighted_2025-07-31 00:00:00,Sum_Weighted_2025-08-29 00:00:00,Sum_Weighted_2025-09-30 00:00:00,Sum_Weighted_2025-10-31 00:00:00,Sum_Weighted_2025-11-28 00:00:00,Sum_Weighted_2025-12-31 00:00:00
0,0.04539,0.028878,-0.010958,-0.003079,0.040071,0.033701,0.003127,0.043579,0.018688,0.009409,0.027036,0.021166